[project]
name = "arxiv-subscription-viewer"
version = "0.1.0"
description = "E-Mail Subscription Viewer for ArXiv"
authors = [
    { name = "Nicolas Sebastian Schuler", email = "nicolas.schuler@kit.edu" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "linkify-it-py>=2.0.3",
    "markdown-it-py>=4.0.0",
    "mdit-py-plugins>=0.5.0",
    "mdurl>=0.1.2",
    "platformdirs>=4.5.1",
    "pygments>=2.19.2",
    "rich>=14.2.0",
    "textual>=7.3.0",
    "typing-extensions>=4.15.0",
    "uc-micro-py>=1.0.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
